// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vxTel.Repository.Context;

namespace vxTel.Repository.Migrations
{
    [DbContext(typeof(VxTelContext))]
    [Migration("20190813221402_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vxTel.Domain.Entities.PlanoTelefonia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AcrescimentoExcedente")
                        .HasColumnName("TaxaAcrescimo");

                    b.Property<DateTime>("ChangedAT")
                        .HasColumnName("DATA_ALTERACAO")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("CreateAT")
                        .HasColumnName("DATA_CRIACAO")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EPlanoTelefonia")
                        .HasColumnName("TIPO");

                    b.Property<Guid>("Guid")
                        .HasColumnName("HASHCODE");

                    b.Property<int>("MinutosPraFalarDeGraca")
                        .HasColumnName("MinutoPlano");

                    b.HasKey("Id");

                    b.ToTable("PlanoTelefonia");
                });

            modelBuilder.Entity("vxTel.Domain.Entities.TarifaLigacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChangedAT")
                        .HasColumnName("DATA_ALTERACAO")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("CreateAT")
                        .HasColumnName("DATA_CRIACAO")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("Guid")
                        .HasColumnName("HASHCODE");

                    b.Property<decimal>("TarifaPorMinuto")
                        .HasColumnName("PRECO_MINUTO")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.ToTable("TarifaTelefonia");
                });

            modelBuilder.Entity("vxTel.Domain.Entities.TarifaLigacao", b =>
                {
                    b.OwnsOne("vxTel.Domain.ValueObjects.DDD", "Destino", b1 =>
                        {
                            b1.Property<int>("TarifaLigacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Code")
                                .HasColumnName("DDD_DESTINO");

                            b1.HasKey("TarifaLigacaoId");

                            b1.ToTable("TarifaTelefonia");

                            b1.HasOne("vxTel.Domain.Entities.TarifaLigacao")
                                .WithOne("Destino")
                                .HasForeignKey("vxTel.Domain.ValueObjects.DDD", "TarifaLigacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("vxTel.Domain.ValueObjects.DDD", "Origem", b1 =>
                        {
                            b1.Property<int>("TarifaLigacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Code")
                                .HasColumnName("DDD_ORIGEM");

                            b1.HasKey("TarifaLigacaoId");

                            b1.ToTable("TarifaTelefonia");

                            b1.HasOne("vxTel.Domain.Entities.TarifaLigacao")
                                .WithOne("Origem")
                                .HasForeignKey("vxTel.Domain.ValueObjects.DDD", "TarifaLigacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
